version: '3'

services: 

  golang:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: golang
    ports:
      - "9000:9000"
    volumes: 
      - ./app:/go/src/
    tty: true